### ISSUE TITLE
https not supported

### ISSUE THREAD

**Issue by maekke97** [holger24/AFD#4]
Hi,

I wanted to get the following configuration up and running:
```
  [directory] noaa_radar
  https://noaa/data\/2D\/MergedReflectivityQCComposite\/

    [dir options]
    inotify 1
    do not remove
    store retrieve list

        [files]
        MRMS_MergedReflectivityQCComposite_00.50_%tY%tm%td-*.grib2.gz

            [destination] bulk015

                        [recipient]
                                exec://my_target/rsync_radar_noaa_1k %s

                                [options]
                                ulock DOT
                                priority 1
```

with the following line in my HOST_CONFIG:
`noaa:mrms.ncep.noaa.gov::::5:10:300:4096:10:-1:120:0:4:1:0:0:0:0:0:0:0:0`

SYSTEM_LOG.0 complains:
`<W> Incorrect url 'https://noaa/data\/2D\/MergedReflectivityQCComposite\/' in DIR_CONFIG_RADAR_NOAA_1K line 1. Error is: unknown scheme. (eval_dir_config.c 914)`

Any idea what I am doing wrong?

Thanks for your help and kind regards

**Comment by holger24** [comment]
Hello,

On Mon, 14 Dec 2020, Markus Neumann wrote:

>
> Hi,
>
> I wanted to get the following configuration up and running:
> `[directory] noaa_radar
> https://noaa/data\/2D\/MergedReflectivityQCComposite\/
>
> [dir options]
> inotify 1
> do not remove
> store retrieve list
>
>     [files]
>     MRMS_MergedReflectivityQCComposite_00.50_%tY%tm%td-*.grib2.gz
>
>         [destination] bulk015
>
>                     [recipient]
>                             exec://my_target/rsync_radar_noaa_1k %s
>
>                             [options]
>                             ulock DOT
>                             priority 1
>
> `
>
> with the following line in my HOST_CONFIG:
> noaa:mrms.ncep.noaa.gov::::5:10:300:4096:10:-1:120:0:4:1:0:0:0:0:0:0:0:0
>
> SYSTEM_LOG.0 complains:
> <W> Incorrect url https://noaa/data\/2D\/MergedReflectivityQCComposite\/' in
> /home/process/afd/etc/DIR_CONFIG_RADAR_NOAA_1K line 1. Error is: unknown
> scheme. (eval_dir_config.c 914)`
>
> Any idea what I am doing wrong?
>
Nothing. The default is to compile AFD without TLS support (so no
https). To enable TLS support one needs to set the configure option
--enable-ssl. In commit 4ac14b7ab97db0dc9aa52c72775cb2a6ed7540cb I just
changed this default so it is enabled by default.

Thanks for reminding me to change this. 15 years ago openssl was not
very common. So this change was long overdue!

Regards,
Holger

**Comment by maekke97** [comment]
Thank you for the response. I will recompile then. :)
Happy Holidays!
